apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-service
  template:
    metadata:
      labels:
        app: application-service
    spec:
      containers:
        - name: application-service
          image: maxwellc21/lokaljob-application-service:latest
          ports:
            - containerPort: 5003
          env:
            - name: MONGO_URI
              value: "mongodb://mongo:27017/applicationsdb"
---
apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    app: application-service
  ports:
    - port: 5003
      targetPort: 5003
